### PR TITLE
Change FIRM setups from 9.0 & 10.2 to 8.1 & 10.0

### PR DESCRIPTION
**Pull request by TheBaloneyboy**
This setup gives us 0x1k more space in stage1 since we're using a perfect key. This code needs cleanup right now, so a direct merge is not recommended. At this point all files are being loaded from the SD card due to hash check failures.

### CODE REVIEW

**Comment by TheBaloneyboy** [comment]
Gonna do some cleanups of history and make a new one, this one's too nasty.

**Comment by ihaveamac** [comment]
I think they can be squashed upon merging?

https://github.com/blog/2141-squash-your-commits

**Comment by TheBaloneyboy** [comment]
Ok, that'd work

**Comment by mariogamer2** [comment]
What is the "alternate stage2"?

**Comment by TheBaloneyboy** [comment]
Alternate stage2 was an idea that @dark-samus had where a recovery payload was placed in NAND for emergencies. With the extra space we get using this FIRM setup, we can make a very minimalist stage1 that can read emergency payloads off of the SD.

**Comment by mariogamer2** [comment]
In fact,it must be closed to be more cleaner,or find a way to do a clean merge of AuroraWright branch (like:

git remote add upstream https://github.com/AuroraWright/SafeA9LHInstaller
git fetch upstream
git merge upstream/master

)

08d532fd7eb16490c3bf97d196bfe5f544fcb141 Must be reverted or reseted too:

git revert longcommitnumber (in this case 08d532fd7eb16490c3bf97d196bfe5f544fcb141)

**Comment by TheBaloneyboy** [comment]
I'm going to close and make this neater, I don't like the way it is right now.

**Comment by AuroraWright** [comment]
I've implemented 8.1 locally (I suggested to use 8.1 initially on Skype to Gelex, since I supposed it might be larger than 9.0, a friend had it luckily), however I don't push because I'm still without my consoles... I've made it so I still have the FIRM0 and secret sector from NAND code, and I don't really want to replace FIRM1 for no reason (as I have had a perfect key for 10.2 FIRM - which is the current FIRM1 - from Gelex for a while).

**Pull request closed without merging**
